version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    image: session-auth/server
  
  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  redis-db:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes: 
      - "redis-data:/data"

volumes:
  postgres-data:
    driver: local

  redis-data:
    driver: local