version: '3.9'
services:
  chat-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8001:8001'
    depends_on:
      - redis-db
      - postgres-db
    image: chat-app

  redis-db:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - 'redis-data:/data'

  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'    

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local